//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Register.WebAPI.FaceDetectionService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="FaceDetectionServiceSoap", Namespace="http://tempuri.org/")]
    public partial class FaceDetectionService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback FaceDetectOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public FaceDetectionService() {
            this.Url = global::Register.WebAPI.Properties.Settings.Default.OCS_Register_WebAPI_FaceDetectionService_FaceDetectionService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event FaceDetectCompletedEventHandler FaceDetectCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/FaceDetect", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public FaceDetectResult FaceDetect(FaceDetectConfig DetectConfig) {
            object[] results = this.Invoke("FaceDetect", new object[] {
                        DetectConfig});
            return ((FaceDetectResult)(results[0]));
        }
        
        /// <remarks/>
        public void FaceDetectAsync(FaceDetectConfig DetectConfig) {
            this.FaceDetectAsync(DetectConfig, null);
        }
        
        /// <remarks/>
        public void FaceDetectAsync(FaceDetectConfig DetectConfig, object userState) {
            if ((this.FaceDetectOperationCompleted == null)) {
                this.FaceDetectOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFaceDetectOperationCompleted);
            }
            this.InvokeAsync("FaceDetect", new object[] {
                        DetectConfig}, this.FaceDetectOperationCompleted, userState);
        }
        
        private void OnFaceDetectOperationCompleted(object arg) {
            if ((this.FaceDetectCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FaceDetectCompleted(this, new FaceDetectCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class FaceDetectConfig {
        
        private string authenCodeField;
        
        private bool enableAutoBrightnessField;
        
        private string transactionIDField;
        
        private bool validateWidthDivideHeightField;
        
        private bool validateFaceRatioField;
        
        private decimal minFacePercentField;
        
        private decimal maxFacePercentField;
        
        private decimal minWidthHeightRatioField;
        
        private decimal maxWidthHeightRatioField;
        
        private string clientIpAddressField;
        
        private int logRunNoField;
        
        private byte[] sourceImageField;
        
        /// <remarks/>
        public string AuthenCode {
            get {
                return this.authenCodeField;
            }
            set {
                this.authenCodeField = value;
            }
        }
        
        /// <remarks/>
        public bool EnableAutoBrightness {
            get {
                return this.enableAutoBrightnessField;
            }
            set {
                this.enableAutoBrightnessField = value;
            }
        }
        
        /// <remarks/>
        public string TransactionID {
            get {
                return this.transactionIDField;
            }
            set {
                this.transactionIDField = value;
            }
        }
        
        /// <remarks/>
        public bool ValidateWidthDivideHeight {
            get {
                return this.validateWidthDivideHeightField;
            }
            set {
                this.validateWidthDivideHeightField = value;
            }
        }
        
        /// <remarks/>
        public bool ValidateFaceRatio {
            get {
                return this.validateFaceRatioField;
            }
            set {
                this.validateFaceRatioField = value;
            }
        }
        
        /// <remarks/>
        public decimal MinFacePercent {
            get {
                return this.minFacePercentField;
            }
            set {
                this.minFacePercentField = value;
            }
        }
        
        /// <remarks/>
        public decimal MaxFacePercent {
            get {
                return this.maxFacePercentField;
            }
            set {
                this.maxFacePercentField = value;
            }
        }
        
        /// <remarks/>
        public decimal MinWidthHeightRatio {
            get {
                return this.minWidthHeightRatioField;
            }
            set {
                this.minWidthHeightRatioField = value;
            }
        }
        
        /// <remarks/>
        public decimal MaxWidthHeightRatio {
            get {
                return this.maxWidthHeightRatioField;
            }
            set {
                this.maxWidthHeightRatioField = value;
            }
        }
        
        /// <remarks/>
        public string ClientIpAddress {
            get {
                return this.clientIpAddressField;
            }
            set {
                this.clientIpAddressField = value;
            }
        }
        
        /// <remarks/>
        public int LogRunNo {
            get {
                return this.logRunNoField;
            }
            set {
                this.logRunNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] SourceImage {
            get {
                return this.sourceImageField;
            }
            set {
                this.sourceImageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class FaceRectangle {
        
        private int widthField;
        
        private int heightField;
        
        private int xField;
        
        private int yField;
        
        /// <remarks/>
        public int Width {
            get {
                return this.widthField;
            }
            set {
                this.widthField = value;
            }
        }
        
        /// <remarks/>
        public int Height {
            get {
                return this.heightField;
            }
            set {
                this.heightField = value;
            }
        }
        
        /// <remarks/>
        public int X {
            get {
                return this.xField;
            }
            set {
                this.xField = value;
            }
        }
        
        /// <remarks/>
        public int Y {
            get {
                return this.yField;
            }
            set {
                this.yField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class FaceDetectResult {
        
        private bool successField;
        
        private string errorMessageField;
        
        private byte[] resultImageField;
        
        private bool isFaceDetectedField;
        
        private bool isBrightnessAdjustField;
        
        private float averageBrightnessField;
        
        private int increaseBrightnessField;
        
        private decimal facePercentField;
        
        private bool isAuthenticatedField;
        
        private FaceRectangle[] faceRectanglesField;
        
        /// <remarks/>
        public bool Success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] ResultImage {
            get {
                return this.resultImageField;
            }
            set {
                this.resultImageField = value;
            }
        }
        
        /// <remarks/>
        public bool IsFaceDetected {
            get {
                return this.isFaceDetectedField;
            }
            set {
                this.isFaceDetectedField = value;
            }
        }
        
        /// <remarks/>
        public bool IsBrightnessAdjust {
            get {
                return this.isBrightnessAdjustField;
            }
            set {
                this.isBrightnessAdjustField = value;
            }
        }
        
        /// <remarks/>
        public float AverageBrightness {
            get {
                return this.averageBrightnessField;
            }
            set {
                this.averageBrightnessField = value;
            }
        }
        
        /// <remarks/>
        public int IncreaseBrightness {
            get {
                return this.increaseBrightnessField;
            }
            set {
                this.increaseBrightnessField = value;
            }
        }
        
        /// <remarks/>
        public decimal FacePercent {
            get {
                return this.facePercentField;
            }
            set {
                this.facePercentField = value;
            }
        }
        
        /// <remarks/>
        public bool IsAuthenticated {
            get {
                return this.isAuthenticatedField;
            }
            set {
                this.isAuthenticatedField = value;
            }
        }
        
        /// <remarks/>
        public FaceRectangle[] FaceRectangles {
            get {
                return this.faceRectanglesField;
            }
            set {
                this.faceRectanglesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void FaceDetectCompletedEventHandler(object sender, FaceDetectCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FaceDetectCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FaceDetectCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public FaceDetectResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((FaceDetectResult)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591